using System.Text;

namespace MonoGame.Editor.Core.CodeGen;

/// <summary>Generates <c>GameBehaviour</c> subclass skeleton source files.</summary>
public sealed class BehaviourSkeletonGenerator : ICodeGenService
{
    private static readonly string[] _allMethods = ["Awake", "Start", "Update", "Draw", "OnDestroy"];

    /// <inheritdoc/>
    public async Task<CodeGenResult> GenerateBehaviourSkeletonAsync(
        string                  className,
        string                  namespaceName,
        string                  relativeFolder,
        IReadOnlyList<string>   lifecycleMethodsToOverride,
        EditorProject           project,
        CancellationToken       cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(project.GameSourcePath))
            return new CodeGenResult(false, string.Empty, "GameSourcePath is not configured.");

        string outputDir = Path.Combine(project.GameSourcePath, relativeFolder);
        Directory.CreateDirectory(outputDir);
        string outputPath = Path.Combine(outputDir, $"{className}.cs");

        if (File.Exists(outputPath))
            return new CodeGenResult(false, outputPath, $"File already exists: {outputPath}");

        string content = BuildSkeletonSource(className, namespaceName, lifecycleMethodsToOverride);

        await File.WriteAllTextAsync(outputPath, content, Encoding.UTF8, cancellationToken)
            .ConfigureAwait(false);

        if (!string.IsNullOrEmpty(project.GameCsprojPath))
            await CsprojFileEditor.EnsureFileIncludedAsync(project.GameCsprojPath, outputPath)
                .ConfigureAwait(false);

        return new CodeGenResult(true, outputPath);
    }

    /// <inheritdoc/>
    public Task<CodeGenResult> GenerateSceneAsync(
        EditorScene     scene,
        EditorProject   project,
        ProjectSettings settings,
        CancellationToken cancellationToken = default)
        => Task.FromResult(new CodeGenResult(false, string.Empty,
            "Use SceneCodeGenerator for scene generation."));

    private static string BuildSkeletonSource(
        string                className,
        string                namespaceName,
        IReadOnlyList<string> methods)
    {
        StringBuilder sb = new();
        sb.AppendLine("// Generated by MonoGame Editor");
        sb.AppendLine("using Alca.MonoGame.Kernel.ECS;");
        sb.AppendLine("using Microsoft.Xna.Framework;");
        sb.AppendLine();
        sb.Append("namespace ");
        sb.Append(namespaceName);
        sb.AppendLine(";");
        sb.AppendLine();
        sb.Append("/// <summary>");
        sb.Append(className);
        sb.AppendLine(" behaviour.</summary>");
        sb.Append("public sealed class ");
        sb.Append(className);
        sb.AppendLine(" : GameBehaviour");
        sb.AppendLine("{");

        for (int i = 0; i < _allMethods.Length; i++)
        {
            string m = _allMethods[i];
            bool include = false;
            for (int j = 0; j < methods.Count; j++)
            {
                if (string.Equals(methods[j], m, StringComparison.Ordinal))
                {
                    include = true;
                    break;
                }
            }
            if (!include) continue;

            if (i > 0 && HasPreviousIncluded(methods, _allMethods, i))
                sb.AppendLine();

            AppendLifecycleMethod(sb, m);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool HasPreviousIncluded(IReadOnlyList<string> chosen, string[] all, int currentIdx)
    {
        for (int i = 0; i < currentIdx; i++)
        {
            for (int j = 0; j < chosen.Count; j++)
            {
                if (string.Equals(chosen[j], all[i], StringComparison.Ordinal))
                    return true;
            }
        }
        return false;
    }

    private static void AppendLifecycleMethod(StringBuilder sb, string name)
    {
        switch (name)
        {
            case "Awake":
                sb.AppendLine("    public override void Awake()");
                sb.AppendLine("    {");
                sb.AppendLine("        base.Awake();");
                break;
            case "Start":
                sb.AppendLine("    public override void Start()");
                sb.AppendLine("    {");
                sb.AppendLine("        base.Start();");
                break;
            case "Update":
                sb.AppendLine("    public override void Update(GameTime gameTime)");
                sb.AppendLine("    {");
                sb.AppendLine("        base.Update(gameTime);");
                break;
            case "Draw":
                sb.AppendLine("    public override void Draw(GameTime gameTime)");
                sb.AppendLine("    {");
                sb.AppendLine("        base.Draw(gameTime);");
                break;
            case "OnDestroy":
                sb.AppendLine("    public override void OnDestroy()");
                sb.AppendLine("    {");
                sb.AppendLine("        base.OnDestroy();");
                break;
        }
        sb.AppendLine("    }");
    }
}
