using System.Security.Cryptography;
using System.Text;

namespace MonoGame.Editor.Core.CodeGen;

/// <summary>
/// Generates <c>{SceneName}Scene.Generated.cs</c> partial class files from the editor scene model.
/// Uses <see cref="StringBuilder"/> directly — no LINQ in the generation loops.
/// </summary>
public sealed class SceneCodeGenerator : ICodeGenService
{
    /// <inheritdoc/>
    public async Task<CodeGenResult> GenerateSceneAsync(
        EditorScene       scene,
        EditorProject     project,
        ProjectSettings   settings,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(project.GameSourcePath))
            return new CodeGenResult(false, string.Empty, "GameSourcePath is not configured.");
        if (string.IsNullOrWhiteSpace(settings.RootNamespace))
            return new CodeGenResult(false, string.Empty, "RootNamespace is not configured in Project Settings.");

        string outputDir  = Path.Combine(project.GameSourcePath, settings.GeneratedCodeFolder, "Scenes");
        string outputPath = Path.Combine(outputDir, $"{scene.Name}Scene.Generated.cs");

        try
        {
            Directory.CreateDirectory(outputDir);

            string content = BuildSceneSource(scene, settings, outputPath);

            bool isNew = !File.Exists(outputPath);
            if (!isNew)
            {
                string existingHash  = ComputeMd5(await File.ReadAllTextAsync(outputPath, cancellationToken).ConfigureAwait(false));
                string newHash       = ComputeMd5(content);
                if (existingHash == newHash)
                    return new CodeGenResult(true, outputPath);
            }

            await File.WriteAllTextAsync(outputPath, content, Encoding.UTF8, cancellationToken)
                .ConfigureAwait(false);

            if (isNew && !string.IsNullOrEmpty(project.GameCsprojPath))
                await CsprojFileEditor.EnsureFileIncludedAsync(project.GameCsprojPath, outputPath)
                    .ConfigureAwait(false);

            return new CodeGenResult(true, outputPath);
        }
        catch (Exception ex)
        {
            return new CodeGenResult(false, outputPath, ex.Message);
        }
    }

    /// <inheritdoc/>
    public Task<CodeGenResult> GenerateBehaviourSkeletonAsync(
        string                className,
        string                namespaceName,
        string                relativeFolder,
        IReadOnlyList<string> lifecycleMethodsToOverride,
        EditorProject         project,
        CancellationToken     cancellationToken = default)
        => new BehaviourSkeletonGenerator().GenerateBehaviourSkeletonAsync(
            className, namespaceName, relativeFolder, lifecycleMethodsToOverride, project, cancellationToken);

    // ──────────────────────────────────────────────────────────
    //  Source generation
    // ──────────────────────────────────────────────────────────

    private static string BuildSceneSource(EditorScene scene, ProjectSettings settings, string outputPath)
    {
        StringBuilder sb = new();
        VariableNameTracker names = new();
        HashSet<string> extraUsings = new(StringComparer.Ordinal);

        string timestamp = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss");
        string relSource  = scene.ScenePath is { Length: > 0 } s ? s : "(unsaved)";

        // Collect extra namespaces from behaviour type names
        List<EditorGameObject> roots = scene.RootGameObjects;
        CollectNamespaces(roots, extraUsings);

        sb.AppendLine($"// AUTO-GENERATED by MonoGame Editor {timestamp} — DO NOT EDIT MANUALLY");
        sb.AppendLine($"// Source: {relSource}");
        sb.AppendLine("// Safe to commit; regenerated automatically on scene save.");
        sb.AppendLine("using Alca.MonoGame.Kernel.ECS;");
        sb.AppendLine("using Microsoft.Xna.Framework;");

        foreach (string ns in extraUsings)
            sb.AppendLine($"using {ns};");

        sb.AppendLine();
        sb.AppendLine($"namespace {settings.RootNamespace}.Scenes;");
        sb.AppendLine();
        sb.AppendLine($"public sealed partial class {scene.Name}Scene : Scene");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Creates and registers all entities defined in the editor scene.</summary>");
        sb.AppendLine("    protected override void OnLoad(GameWorld world)");
        sb.AppendLine("    {");

        for (int i = 0; i < roots.Count; i++)
            AppendEntity(sb, roots[i], null, names, indent: "        ");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void CollectNamespaces(List<EditorGameObject> objects, HashSet<string> namespaces)
    {
        for (int i = 0; i < objects.Count; i++)
        {
            EditorGameObject obj = objects[i];
            List<EditorBehaviour> behaviours = obj.Behaviours;
            for (int j = 0; j < behaviours.Count; j++)
            {
                string ns = ExtractNamespace(behaviours[j].TypeName);
                if (!string.IsNullOrEmpty(ns)
                    && ns != "Alca.MonoGame.Kernel.ECS"
                    && ns != "Microsoft.Xna.Framework")
                {
                    namespaces.Add(ns);
                }
            }
            CollectNamespaces(obj.Children, namespaces);
        }
    }

    private static string ExtractNamespace(string typeName)
    {
        int dot = typeName.LastIndexOf('.');
        return dot > 0 ? typeName[..dot] : string.Empty;
    }

    private static void AppendEntity(
        StringBuilder        sb,
        EditorGameObject     entity,
        string?              parentVarName,
        VariableNameTracker  names,
        string               indent)
    {
        string varName = names.Allocate(ToCamelCase(entity.Name));

        sb.AppendLine();
        sb.AppendLine($"{indent}// ── Entity: {entity.Name} {new string('─', Math.Max(0, 64 - entity.Name.Length))}");
        sb.Append($"{indent}var {varName} = world.CreateEntity(\"{EscapeString(entity.Name)}\"");
        sb.AppendLine($", new Vector2({FormatFloat(entity.Position.X)}, {FormatFloat(entity.Position.Y)}));");

        if (parentVarName is not null)
            sb.AppendLine($"{indent}{varName}.SetParent({parentVarName});");

        List<EditorBehaviour> behaviours = entity.Behaviours;
        for (int i = 0; i < behaviours.Count; i++)
        {
            EditorBehaviour b       = behaviours[i];
            string          bShort  = GetShortTypeName(b.TypeName);
            string          bVar    = names.Allocate(ToCamelCase(bShort));

            sb.AppendLine($"{indent}var {bVar} = {varName}.AddComponent<{bShort}>();");

            foreach (KeyValuePair<string, JsonElement> prop in b.Properties)
                AppendPropertyAssignment(sb, bVar, prop.Key, prop.Value, indent);
        }

        List<EditorGameObject> children = entity.Children;
        for (int i = 0; i < children.Count; i++)
            AppendEntity(sb, children[i], varName, names, indent);
    }

    private static void AppendPropertyAssignment(
        StringBuilder sb,
        string        varName,
        string        propName,
        JsonElement   value,
        string        indent)
    {
        string? literal = ResolvePropertyLiteral(value);
        if (literal is null) return;

        sb.AppendLine($"{indent}{varName}.{propName} = {literal};");
    }

    private static string? ResolvePropertyLiteral(JsonElement value)
    {
        switch (value.ValueKind)
        {
            case JsonValueKind.True:  return "true";
            case JsonValueKind.False: return null; // false is the default for bool, skip
            case JsonValueKind.String:
            {
                string s = value.GetString() ?? string.Empty;
                if (s.Length == 0) return null; // empty string is the default, skip
                return $"\"{EscapeString(s)}\"";
            }
            case JsonValueKind.Number:
            {
                if (value.TryGetInt32(out int i))
                {
                    if (i == 0) return null; // 0 is the default, skip
                    return i.ToString();
                }
                if (value.TryGetDouble(out double d))
                {
                    if (d == 0.0) return null; // 0.0 is the default, skip
                    return $"{d}f";
                }
                return null;
            }
            case JsonValueKind.Object:
            {
                // Try Color { R, G, B, A }
                if (value.TryGetProperty("R", out JsonElement r) &&
                    value.TryGetProperty("G", out JsonElement g) &&
                    value.TryGetProperty("B", out JsonElement b) &&
                    value.TryGetProperty("A", out JsonElement a))
                {
                    int ri = r.TryGetInt32(out int rv) ? rv : 0;
                    int gi = g.TryGetInt32(out int gv) ? gv : 0;
                    int bi2 = b.TryGetInt32(out int bv) ? bv : 0;
                    int ai = a.TryGetInt32(out int av) ? av : 255;
                    if (ri == 0 && gi == 0 && bi2 == 0 && ai == 255) return null;
                    return $"new Color({ri}, {gi}, {bi2}, {ai})";
                }
                // Try Vector3 { X, Y, Z }
                if (value.TryGetProperty("X", out JsonElement x) &&
                    value.TryGetProperty("Y", out JsonElement y) &&
                    value.TryGetProperty("Z", out JsonElement z))
                {
                    float xf = (float)x.GetDouble();
                    float yf = (float)y.GetDouble();
                    float zf = (float)z.GetDouble();
                    if (xf == 0f && yf == 0f && zf == 0f) return null;
                    return $"new Vector3({FormatFloat(xf)}, {FormatFloat(yf)}, {FormatFloat(zf)})";
                }
                // Try Vector2 { X, Y }
                if (value.TryGetProperty("X", out JsonElement x2) &&
                    value.TryGetProperty("Y", out JsonElement y2))
                {
                    float xf = (float)x2.GetDouble();
                    float yf = (float)y2.GetDouble();
                    if (xf == 0f && yf == 0f) return null;
                    return $"new Vector2({FormatFloat(xf)}, {FormatFloat(yf)})";
                }
                return null;
            }
            default: return null;
        }
    }

    // ──────────────────────────────────────────────────────────
    //  Helpers
    // ──────────────────────────────────────────────────────────

    private static string FormatFloat(float v) => $"{v:G}f";

    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string GetShortTypeName(string typeName)
    {
        int dot = typeName.LastIndexOf('.');
        return dot >= 0 ? typeName[(dot + 1)..] : typeName;
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return "entity";

        StringBuilder sb = new(name.Length);
        bool nextUpper = false;
        bool first = true;
        for (int i = 0; i < name.Length; i++)
        {
            char c = name[i];
            if (!char.IsLetterOrDigit(c)) { nextUpper = !first; continue; }
            if (first) { sb.Append(char.ToLowerInvariant(c)); first = false; }
            else if (nextUpper) { sb.Append(char.ToUpperInvariant(c)); nextUpper = false; }
            else sb.Append(c);
        }

        return sb.Length == 0 ? "entity" : sb.ToString();
    }

    private static string ComputeMd5(string content)
    {
        byte[] bytes = Encoding.UTF8.GetBytes(content);
        byte[] hash  = MD5.HashData(bytes);
        return Convert.ToHexString(hash);
    }

    // ──────────────────────────────────────────────────────────
    //  Variable name tracker (collision avoidance)
    // ──────────────────────────────────────────────────────────

    private sealed class VariableNameTracker
    {
        private readonly Dictionary<string, int> _counts = new(StringComparer.Ordinal);

        public string Allocate(string baseName)
        {
            if (!_counts.TryGetValue(baseName, out int count))
            {
                _counts[baseName] = 1;
                return $"{baseName}_0";
            }

            _counts[baseName] = count + 1;
            return $"{baseName}_{count}";
        }
    }
}
